yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordResetView, PasswordChangeDoneView,
    PasswordResetDoneView, PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_change/',
         PasswordChangeView.as_view(
         template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_change_done/',
         PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/',
         PasswordResetView.as_view(
         template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
         template_name='users/password_reset_complete.html'),
         name='password_reset_compete')
]

yatube/yatube/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField('Содержание поста')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ('-pub_date',)
    
    def __str__(self) -> str:
        return self.text


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Группа', unique=True)
    description = models.TextField('Описание')

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text')
        help_text = {
            'text': '*Введите текст поста',
            'group': 'Выберите группу, к которой будет относиться пост'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from .models import Group, Post, User
from .forms import PostForm

POSTS_ON_PAGE: int = 10


def paginator_object(request, post_list):
    paginator = Paginator(post_list, POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    title = 'Последние обновления на сайте'
    post_list = Post.objects.all()
    page_obj = paginator_object(request, post_list)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    title = 'Здесь будет информация о группах проекта Yatube'
    post_list = group.posts.all()
    page_obj = paginator_object(request, post_list)
    context = {
        'group': group,
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    page_obj = paginator_object(request, post_list)
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_number = post.author.posts.count()
    context = {
        'post': post,
        'post_number': post_number
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create(request):
    form = PostForm(request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)
    is_edit = True
    context = {
        'form': form,
        'is_edit': is_edit,
        'post_id': post_id,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm

class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% load static %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Hi, i'm Maksim Moryakov 👋</h1>
<p>I'm a junior programmer.</p>
<p>My profile GITHub <a href="https://github.com/maksim-moryakov">Maksim-Moryakov</a></p>
<p>Project_1: 🔬 «Learn to learn» - one-page portfolio website. 
  Link to the project: <a href="https://maksim-moryakov.github.io/how-to-learn/">How-to-learn/</a>
</p>
<p>Project_2: 🗺 «Travel to Russia» - a project about traveling in Russia. 
  Link to the project: <a href="https://maksim-moryakov.github.io/russian-travel/">Russian-travel/</a>
</p>
<p>
  Project_3: 🏡 «Place» - an interactive page, where you can add photos, delete them and put likes.
  Link to the project: <a href="https://maksim-moryakov.github.io/mesto/">Mesto</a>
</p>
<p>
  Project_4: ✈️ «Weekend competition» - a joint project with a classmate as part of a weekend competition
  Link to the project: <a href="https://maksim-danil.github.io/weekend_competition/">Weekend_competitio</a>
</p>
<p>Now I am learning a new programming language Python.</p>
<p>🔨 My stack: HTML; CSS; Javascript; Python; Django.</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <h3>Настройка и запуск</h3>
    <p>1. Склонировать проект:</p>
    <p>
      git clone <a href="https://github.com/maksim-moryakov/hw02_community.git"></a>
    </p>
    <p>- Моряков Максим</p>
    <p>- Email: maksim.moryakov@gmail.com </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">    
  <head> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
    {% block header %}{% endblock %}
  </head>
  <body class="container">       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {% now "jS F Y H:i" %} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
        </a>
        <ul class="nav nav-pills">
          {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
              href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
              href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item nav-link link-light">
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
          {% endwith %} 
        </ul>
    </div>
  </nav>
</header>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}

{% block content %}  
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост 
          {% endif %}       
        </div>
        <div class="card-body">
          {% if is_edit %}        
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create'%}">
          {% endif %}
          {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text}}
              <small class="form-text text-muted">Текст нового поста</small>
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группа                  
              </label>
              {{ form.group }}
              <small class="form-text text-muted">Группа, к которой будет относиться пост</small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}     
              </button>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %} 
  <h1>{{ group }}</h1>
    {% for post in page_obj %}
      <br>Автор: {{ post.author.get_full_name }},
      <br>Дата публикации: {{ post.pub_date|date:"d E Y" }}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if not forloop.last %}
      <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} {{ post|truncatechars:30 }} {% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}: {{ post.group.description }}
              <br>
              <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item">
            Всего постов пользователя: {{ posts_count }}
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p> {{ post }} </p>
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">Редактировать запись</a>
        {% endif %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}{{ author.get_full_name }} Профайл пользователя{% endblock %}

{% block content %}       
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ page_obj.paginator.count }}</h3>   
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p> {{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация</a>
      <br>
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
      {% endif %}
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% load static %}
{% block title %}Пароль изменён{% endblock title %}
{% block content %}
    <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    {{form.old_password}}
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>
                    {{form.new_password1}}
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul>
                          <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>
                    {{form.new_password2}}
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">Войти</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}
{% if validlink %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Введите новый пароль
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
              <small id="id_new_password1-help" class="form-text text-muted">
                <ul>
                  <li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li>
                  <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                  <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                  <li>Ваш пароль не может состоять только из цифр.</li>
                </ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock title %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Отправлено письмо
            </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load static %}
{% block title %} Сброс пароля {% endblock title %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                <label for="id_email">
                    Адрес электронной почты
                    <span class="required text-danger">*</span>
                </label>    
                {{form.email}}
                </div>
                <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Сбросить пароль
                </button>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
              </button>
            </div>
            </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 